// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "todos-20181018153832--hostingbucket",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "https://d1req4yjq8kck9.cloudfront.net",
    "aws_cognito_identity_pool_id": "ap-northeast-1:827b0679-e1f6-4c9b-8610-883b727a00ef",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_1z2qv3a2m",
    "aws_user_pools_web_client_id": "6dqa4v7n1g992dlhjf49lfjcvs",
    "aws_user_files_s3_bucket": "todosc11c4cc8bb6046eaa21fd6b5490ca0aa",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_appsync_graphqlEndpoint": "https://htvskvkk6vajtk7hkgbvxa2fcm.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
